# $OpenBSD: Makefile,v 1.30 2020/04/12 14:26:02 sthen Exp $

PORTROACH=	limit:^7\.4
PHP_VERSION=	7.4.4
PHP_PKGSPEC=	>=7.4,<8.0

DEFAULT_PHP=	Yes

DEBUG_PACKAGES=		${BUILD_PACKAGES}

.include <bsd.port.mk>
